-- noinspection SqlDialectInspectionForFile
# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "email" varchar not null,
  "login" varchar not null,
  "password" varchar not null
);

create table "item" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "itemType" int not null,
  "ownerId" bigint not null,
  "lentId" bigint,
  FOREIGN KEY ("ownerId") REFERENCES "people"("id"),
  FOREIGN KEY ("lentId") REFERENCES "people"("id")
);

# --- !Downs

drop table "people" if exists;
drop table "item" if exists;
